package com.qxj.springboot.dataobject;

import lombok.Data;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@Data
@Table(name = "min1_trade_data")
public class TradeDataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.id
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "SELECT LAST_INSERT_ID()")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.unit
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.ticker
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    private String ticker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.shortnm
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    private String shortnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.bar_time
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "bar_time")
    private Date barTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.open_price
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "open_price")
    private BigDecimal openPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.close_price
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "close_price")
    private BigDecimal closePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.low_price
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "low_price")
    private BigDecimal lowPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.high_price
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "high_price")
    private BigDecimal highPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.total_value
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "total_value")
    private BigDecimal totalValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.total_volume
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    @Column(name = "total_volume")
    private Integer totalVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.vwap
     *
     * @mbg.generated Wed Oct 23 22:23:50 CST 2019
     */
    private BigDecimal vwap;

}